<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>


<style>
    a:link,
    a:visited
    {
        color: #0398CA;
    }

    div#welcome
    {
        //color: #000000;
        color: #002EB8;
        overflow: hidden;
        text-align: center;
        margin-left: 10%;
        margin-right: 10%;
    }

    .box{
        border-radius: 25px 25px 25px 25px;
        -moz-border-radius: 25px 25px 25px 25px;
        -webkit-border-radius: 25px 25px 25px 25px;
        border: 2px solid #002EB8;
        background-color: #ffffff;  
        padding: 10px;
        margin: 0px auto;

        color: #002EB8;
        font-weight: bold;
        font-size: 16px;
    }
</style>
<div id="welcome">
    <p class="box">
        As a department of the Allen County Public Library, the Audio Reading Service is primarily designed for, and directed to, people who have a visual or reading impairment, including any individual who is unable to read conventional printed material because of blindness, low-vision, a literacy issue, or a physical impairment which makes it difficult to hold a book or turn pages such as stroke, MS, Parkinson’s or arthritis.
    </p>
</div>
