<style>
    a:link,
    a:visited
    {
        color: #0398CA;
    }

    div#welcome
    {
        color: #000000;
        overflow: hidden;
        text-align: center;
        margin-left: 10%;
        margin-right: 10%;
    }

    div#logo
    {
        background-color: white;
        height: 100%;
    }
</style>
<div id="welcome">
    <h1>Welcome to the Allen County Public Library!</h1>

    <p>
        <img src="http://static1.1.sqspcdn.com/static/f/853277/15535284/1323521278497/sponsorACPLLogo.jpg?token=TuaN%2Bvw9UOWKSOxOtDGvs73AXEE%3D" />
    </p>
    
</div>