<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>


<style>
    a:link,
    a:visited
    {
        color: #0398CA;
    }

    div#welcome
    {
        //color: #000000;
        color: #002EB8;
        overflow: hidden;
        text-align: center;
        margin-left: 10%;
        margin-right: 10%;
        
    }

    div#logo
    {
        background-color: white;
        height: 100%;
    }
</style>
<div id="welcome">
    <h1>Welcome to the Allen County Public Library!</h1>

    <p>
        <img src="http://static1.1.sqspcdn.com/static/f/853277/15535284/1323521278497/sponsorACPLLogo.jpg?token=TuaN%2Bvw9UOWKSOxOtDGvs73AXEE%3D" />
    </p>
    
</div>