<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1">
            <title>Audio Reading Service</title>
            <!-- css files -->
            <?php $this->headLink()->appendStylesheet($this->baseUrl('/css/bootstrap-3.3.5.min.css')) ?>
            <?php $this->headLink()->appendStylesheet($this->baseUrl('/css/site.css')) ?>
            <?php $this->headLink()->appendStylesheet($this->baseUrl('/css/dateselector.css')) ?>
            <?php echo $this->headLink()->appendStylesheet($this->baseUrl('/css/styles.css')) ?>
            <?php //echo $this->headLink()->appendStylesheet($this->baseUrl('/css/admin.css')) ?>

            <!-- javascript files -->
            <?php $this->headScript()->prependFile($this->baseUrl('/js/jquery.dateselector.min.js')) ?>
            <?php $this->headScript()->prependFile($this->baseUrl('/js/moment.min.js')) ?>
            <?php $this->headScript()->prependFile($this->baseUrl('/js/dist/jquery.date-dropdowns.js')) ?>
            <?php $this->headScript()->prependFile($this->baseUrl('/js/mask/jquery.maskedinput.js')) ?>

            <!-- js file for admin interface ---------------- uncomment later -->
            <?php //$this->headScript()->prependFile($this->baseUrl('/js/admin.js')) ?>
            
            <?php $this->headScript()->prependFile($this->baseUrl('/js/bootstrap-3.3.5.min.js')) ?>
            <?php echo $this->headScript()->prependFile($this->baseUrl('/js/jquery-1.11.3.min.js')) ?>

    </head>
    <body>
        <label class="brand pull-left">
            <img src="http://www.acpl.lib.in.us/images/default-source/logos/ars-logo-blue-acpl-web-01-final.tmb-medium.png?sfvrsn=3" />
        </label>

        <div class="container">
            <nav>
                <ul class="nav nav-tabs nav-justified">

                    <li class="active" role="presentation">
                        <a href="<?php
                        echo $this->url(
                                array('controller' => 'Index'), 'default', true)
                        ?>">Home</a>
                    </li>

                    <!--
                    <li role="presentation">
                        <a href="<?php
                        //echo $this->url(
                          //      array('controller' => 'Admin', 'action' => 'admin'), 'default', true)
                        ?>">Admin Interface</a>
                    </li>
                    -->
                    
                    <li role="presentation">
                        <a href="<?php
                        echo $this->url(
                                array('controller' => 'Login', 'action' => 'login'), 'default', true)
                        ?>">Admin</a>
                    </li>

                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Radio Applications<span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li role="presentation" ><a href="<?php
                                echo $this->url(
                                        array('controller' => 'RadioApplication', 'action' => 'radio-form'), 'default', true)
                                ?>">Individual Application</a></li>
                            <li role="presentation" ><a href="<?php
                                echo $this->url(
                                        array('controller' => 'RadioApplication', 'action' => 'organization-form'), 'default', true)
                                ?>">Application for Organizations</a></li>

                            <li role="separator" class="divider"></li>

                            <li role="presentation" ><a href="<?php
                                echo $this->url(
                                        array('controller' => 'ReturnRadio', 'action' => 'return'), 'default', true)
                                ?>">Return a Radio</a></li>
                        </ul>
                    </li>
                </ul>
            </nav>
        </div>

        <br /><br />
        <?php echo $this->layout()->content ?>


        <script>
            $('.dropdown-toggle').dropdown();
        </script>

    </body>
</html>
