<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Audio Reading Service</title>
        <?php echo $this->headLink()->appendStylesheet($this->baseUrl('/css/site.css')) ?>
        <?php echo $this->headScript()->prependFile($this->baseUrl('/css/jquery-1.11.3.min.js')) ?>
    </head>
    <body>
        <div id="header" style="background-color: #EEEEEE; height: 30px;">
            <div id="header-logo" style="float: left">
                <b>Allen County Public Library</b>
            </div>
            <div id="header-navigation" style="float: right">
                <a href="<?php
                echo $this->url(
                        array('controller' => 'Index'), 'default', true)
                ?>">Home</a>
                
                <?php echo " | " ?>
                
                <a href="<?php
                echo $this->url(
                        array('controller' => 'RadioApplication'), 'default', true)
                ?>">Audio Reading Service</a>
            </div>
        </div>

        <br /><br />
        <?php echo $this->layout()->content ?>

    </body>
</html>
