<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Audio Reading Service</title>
        <?php echo $this->headLink()->appendStylesheet($this->baseUrl('/css/site.css')) ?>
        <?php echo $this->headScript()->prependFile($this->baseUrl('/css/jquery-1.11.3.min.js')) ?>
        <?php echo $this->headScript()->prependFile($this->baseUrl('/js/jquery.js')) ?>

        <?php echo $this->headScript()->prependFile("http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css") ?>

        <?php echo $this->headScript()->prependFile('http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js') ?>
    </head>
    <body>
        <div class="container">
            <ul class="nav nav-tabs nav-justified">
                <li role="presentation">Allen County Public Library</li>
                <li role="presentation"><a href="<?php
                    echo $this->url(
                            array('controller' => 'Index'), 'default', true)
                    ?>">Home</a></li>
                <li role="presentation" ><a href="<?php
                    echo $this->url(
                            array('controller' => 'RadioApplication'), 'default', true)
                    ?>">Audio Reading Service</a></li>
            </ul>
        </div>

        <br /><br />
        <?php echo $this->layout()->content ?>

    </body>
</html>
