<style>
    h1{
        color: #002EB8;
    }
    
    .listener{
        clear: left;
    }

    .section{
        display: inline-block;
    }

    label.key{
        display: inline-block;
        width: 200px;
        float: left;
        font-weight: bold;
        text-align: right;
    }

    label.value{
        width: 300px;
        margin-left: 20px;
        float: left;
    }
</style>


<?php
session_start();

// get session variables from form
$listenerData = $_SESSION['data']['postData']['listener'];
$contactData = $_SESSION['data']['postData']['contact'];
$otherInfoData = $_SESSION['data']['postData']['otherInfo'];
$statementData = $_SESSION['data']['postData']['statement'];

echo "<h1>Review Your Information and Submit</h1>";


// ================================================= Listener
echo "<div class='listener'>";
echo "<h2>Listener</h2>";
foreach ($listenerData as $key => $value) {
    echo "<div class='section'><label class='key'>$key : </label> <label class='value'>$value</label></div>";
}
echo "</div>";

// ================================================= Contact
echo "<div class='contact'>";
echo "<h2>Contact</h2>";
foreach ($contactData as $key => $value) {
    echo "<div class='section'><label class='key'>$key : </label> <label class='value'>$value</label></div>";
}
echo "</div>";

// ================================================= Other Info
echo "<div class='otherInfo'>";
echo "<h2>Other Info</h2>";
foreach ($otherInfoData as $key => $value) {
    echo "<div class='section'><label class='key'>$key : </label> <label class='value'>$value</label></div>";
}
echo "</div>";

// ================================================= Statement
echo "<div class='statement'>";
echo "<h2>Statement</h2>";
foreach ($statementData as $key => $value) {
    echo "<div class='section'><label class='key'>$key : </label> <label class='value'>$value</label></div>";
}
echo "</div>";

// =================================================

$this->form->setAction($this->url());
echo $this->form;

