<!-- Confirmation page for Organization radio applications -->
<style>
    .borderless{
        border: none;
    }
</style>

<div class="container">
    <?php
    session_start();

    // get session variables from form
    $organizationData = $_SESSION['data']['postData']['organizationForm'];
    $statementData = $_SESSION['data']['postData']['statementForm'];

    // =============================================== format phone numbers - refactor

    function formatPhone($phone) {
        //$phone = 12343435556; // 11-digit phone number
        if (strlen($phone) < 11) {  // area code and phone number
            return substr($phone, 0, 3) . '.' . substr($phone, 3, 3) . '.' . substr($phone, 6);
        } else {
            return substr($phone, 0, 1) . '.' . substr($phone, 1, 3) . '.' . substr($phone, 4, 3) . '.' . substr($phone, 7);
        }
    }

    // ===============================================

    echo "<h1>Review Your Information and Submit</h1>";
    echo "<hr/>";
    ?>

    <div id="organizationReview">
        <div class="panel-group">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    Organization Information
                </div>
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class="table table-condensed" style="border:none;">

                            <td> 
                                <table class="table table-condensed " style="border:none;">
                                    <tbody>
                                        <tr>
                                            <th scope="row" class="review-label" style="border:none;">Organization Name:</th>
                                            <td style="border:none;"><?php echo $organizationData['OrgName']; ?></td>
                                        </tr>
                                        <tr>
                                            <th scope="row" class="review-label" style="border:none;">Organization Type:</th>
                                            <td style="border:none;"><?php echo $organizationData['OrgType']; ?></td>
                                        </tr>
                                        <tr>
                                            <th scope="row" class="review-label" style="border:none;">Staff Rep. Organization:</th>
                                            <td style="border:none;"><?php echo $organizationData['FirstName'] . " " . $organizationData['LastName'] . " / " . $organizationData['PositionTitle']; ?></td>
                                        </tr>

                                        <tr>
                                            <th scope="row" class="review-label" style="border:none;">Address Line 1:</th>
                                            <td style="border:none;"><?php echo $organizationData['Address']; ?></td>
                                        </tr>
                                        <tr>
                                            <th scope="row" class="review-label" style="border:none;">Address Line 2:</th>
                                            <td style="border:none;"><?php echo $organizationData['AlternativeAddress']; ?></td>
                                        </tr>
                                        <tr>
                                            <th scope="row" class="review-label" style="border:none;">City/State/Zipcode:</th>
                                            <td style="border:none;"><?php echo $organizationData['City'] . ", " . $organizationData['State'] . " " . $organizationData['Zip']; ?></td>
                                        </tr>

                                        <tr>
                                            <th scope="row" class="review-label" style="border:none;">Office Phone #:</th>
                                            <td style="border:none;"><?php echo $organizationData['OfficePhone']; ?></td>
                                        </tr>
                                        <tr>
                                            <th scope="row" class="review-label" style="border:none;">Cell Phone #:</th>
                                            <td style="border:none;"><?php echo $organizationData['CellPhone']; ?></td>
                                        </tr>
                                        <tr>
                                            <th scope="row" class="review-label" style="border:none;">Email:</th>
                                            <td style="border:none;"><?php echo $organizationData['Email']; ?></td>
                                        </tr>
                                    </tbody>
                                </table>
                            </td>

                            <td>
                                <table class="table table-condensed table-borderless" style="border:none;">
                                    <tbody>
                                        <tr>
                                            <th scopre="row" class="review-label" style="border:none;">Radios Requested:</th>
                                            <td style="border:none;"><?php echo $organizationData['RadioNum']; ?></td>
                                        </tr>
                                        <tr>
                                            <th scopre="row" class="review-label" style="border:none;">Number of Licensed Beds:</th>
                                            <td style="border:none;"><?php echo $organizationData['LicBedsNum']; ?></td>
                                        </tr>
                                        <tr>
                                            <th scopre="row" class="review-label" style="border:none;">Number of Residential Units:</th>
                                            <td style="border:none;"><?php echo $organizationData['ResUnitsNum']; ?></td>
                                        </tr>

                                        <tr>
                                            <th scopre="row" class="review-label" style="border:none;">How You Learned About Our Service:</th>
                                            <td style="border:none;"><?php echo $organizationData['HowLearn']; ?></td>
                                        </tr>
                                    </tbody>
                                </table>
                            </td>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- ================================================= Organization -->
    <div class="panel panel-primary">
        <div class="panel-heading">Signature of Responsible Party:</div>
        <div class="panel-body">
            <?php echo $statementData['Signature'] . " submitted form on: " . date("F j, Y"); ?>
        </div>
    </div>

    <!--// =================================================-->
    <?php
        $this->form->setAction($this->url());
        echo $this->form;
    ?>
</div>
