<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>


<div class="container">
    <?php
    session_start();

// get session variables from form
    $listenerData = $_SESSION['data']['postData']['listener'];
    $contactData = $_SESSION['data']['postData']['contact'];
    $otherInfoData = $_SESSION['data']['postData']['otherInfo'];
    $statementData = $_SESSION['data']['postData']['statement'];

    echo "<h1>Review Your Information and Submit</h1>";
    echo "<hr />"
    ?>

    <!--================================================= Listener-->
    <div class="panel panel-primary">
        <div class="panel-heading">Listener</div>
        <div class="panel-body">
            <?php
            foreach ($listenerData as $key => $value) {
                echo "<div class='section'><label class='key'>$key : </label> <label class='value'>$value</label></div>";
            }
            ?>
        </div>
    </div>

    <!--// ================================================= Contact-->
    <div class="panel panel-primary">
        <div class="panel-heading">Contact</div>
        <div class="panel-body">
            <?php
            foreach ($contactData as $key => $value) {
                echo "<div class='section'><label class='key'>$key : </label> <label class='value'>$value</label></div>";
            }
            ?>
        </div>
    </div>

    <!--// ================================================= Other Info-->
    <div class="panel panel-primary">
        <div class="panel-heading">Other Info</div>
        <div class="panel-body">
            <?php
            foreach ($otherInfoData as $key => $value) {
                echo "<div class='section'><label class='key'>$key : </label> <label class='value'>$value</label></div>";
            }
            ?>
        </div>
    </div>

    <!--// ================================================= Statement-->
    <div class="panel panel-primary">
        <div class="panel-heading">Statement</div>
        <div class="panel-body">
            <?php
            foreach ($statementData as $key => $value) {
                echo "<div class='section'><label class='key'>$key : </label> <label class='value'>$value</label></div>";
            }
            ?>
        </div>
    </div>

    <!--// =================================================-->
    <?php
    $this->form->setAction($this->url());
    echo $this->form;
    ?>
</div>