<!-- Confirmation page for Organization radio applications -->


<div class="container">
    <?php
    session_start();

    // get session variables from form
    $organizationData = $_SESSION['data']['postData']['organization'];
    $statementData = $_SESSION['data']['postData']['statement'];

    // =============================================== format phone numbers - refactor

    function formatPhone($phone) {
        //$phone = 12343435556; // 11-digit phone number
        if (strlen($phone) < 11) {  // area code and phone number
            return substr($phone, 0, 3) . '.' . substr($phone, 3, 3) . '.' . substr($phone, 6);
        } else {
            return substr($phone, 0, 1) . '.' . substr($phone, 1, 3) . '.' . substr($phone, 4, 3) . '.' . substr($phone, 7);
        }
    }

    // ===============================================

    echo "<h1>Review Your Information and Submit</h1>";
    echo "<hr/>";
    ?>


    <!-- ================================================= Organization -->
    <div class="panel panel-primary">
        <div class="panel-heading">Organization</div>
        <div class="panel-body">

            <?php


            foreach ($organizationData as $key => $value) {
                if (strpos($key, 'phone') !== false || strpos($key, 'Phone') !== false) {
                    $value = formatPhone($value);
                    echo "<div class='section'><label class='key'>$key : </label> <label class='value'>$value</label></div>";
                } else {
                    echo "<div class='section'><label class='key'>$key : </label> <label class='value'>$value</label></div>";
                }
            }
            ?>
        </div>
    </div>

    <!-- ================================================= Statement -->
    <div class="panel panel-primary">
        <div class="panel-heading">Statement</div>
        <div class="panel-body">
            <?php
            foreach ($statementData as $key => $value) {
                echo "<div class='section'><label class='key'>$key : </label> <label class='value'>$value</label></div>";
            }
            ?>
        </div>
    </div>

    <!--// =================================================-->
    <?php
    $this->form->setAction($this->url());
    echo $this->form;
    ?>
</div>
