<style>
    .ars-color{
        color: #002EB8;
        font-weight: bold;
    }
</style>

<div id="acpl-header">
    <h2 class="ars-color">APPLICATION FOR AUDIO READING SERVICE RADIO</h2>
    
    <section id="acpl-left-header" >
        Allen County Public Library<br />
        <span class="ars-color">Audio Reading Service</span><br />
        7615 DiSalle Blvd.<br />
        Fort Wayne, IN 46825<br />
    </section>
    
    <section id="acpl-right-header" >
        Phone: (260) 421-1376<br />
        Fax: (260) 421-1387<br />
        AudioReadingService@acpl.info<br />
    </section>
</div>