<style>
    #acpl-header{
        color: #002EB8;
        font-size: 18px;
        font-weight: bold;
        text-align: center;
    }
</style>

<div id="acpl-header">
    <img src="http://www.acpl.lib.in.us/images/default-source/logos/ars-logo-blue-acpl-web-01-final.tmb-medium.png?sfvrsn=3" alt="Audio Reading Service"/>


    <h4>REQUEST FROM AN ORGANIZATION</h4>
    <h4>FOR AUDIO READING SERVICE RADIOS</h4>

    <p>
        Allen County Public Library * Audio Reading Service
    </p>

    <p>
        7615 DiSalle Blvd * Fort Wayne IN 46825 * 260.421.1376
    </p>

    <p>
        AudioReadingService@acpl.info
    </p>
</div>