<style>
    #acpl-header{
        color: #002EB8;
        font-size: 18px;
        font-weight: bold;
        text-align: center;
    }
</style>

<div id="acpl-header">
    <img src="http://www.acpl.lib.in.us/images/default-source/logos/ars-logo-blue-acpl-web-01-final.tmb-medium.png?sfvrsn=3" alt="Audio Reading Service"/>

    <h2>APPLICATION FOR AUDIO READING SERVICE RADIO</h2>
    
    <p>
        Allen County Public Library * Audio Reading Service
    </p>
    
    <p>
        7615 DiSalle Blvd * Fort Wayne IN 46825 * 260.421.1376
    </p>
    
    <p>
        AudioReadingService@acpl.info
    </p>
    
    
<!--    <section id="acpl-left-header" >
        Allen County Public Library<br />
        <span class="ars-color">Audio Reading Service</span><br />
        7615 DiSalle Blvd.<br />
        Fort Wayne, IN 46825<br />
    </section>
    
    <section id="acpl-right-header" >
        Phone: (260) 421-1376<br />
        Fax: (260) 421-1387<br />
        AudioReadingService@acpl.info<br />
    </section>-->
</div>