<style>
    a:link,
    a:visited
    {
        color: #0398CA;
    }

    div#view-content
    {
        color: #002EB8;
        overflow: hidden;
        text-align: center;
        margin-left: 10%;
        margin-right: 10%;
    }

</style>

<br />
<div id="view-content" >
    <h1>Welcome to the Audio Reading Service!</h1>

    <p>
        <img src="http://www.acpl.lib.in.us/images/default-source/logos/ars-logo-blue-acpl-web-01-final.tmb-medium.png?sfvrsn=3" />
    </p>
    
    <p><a href="<?php
        echo $this->url(
                array(
            'controller' => 'RadioApplication',
            'action' => 'radio-form'
                ), 'default', true)
        ?>">Radio Application</a></p>

</div>