<style>
    #acpl-header{
        color: #002EB8;
        font-size: 18px;
        font-weight: bold;
        text-align: center;
    }    
    
    .box{
        border-radius: 33px 33px 33px 33px;
        -moz-border-radius: 33px 33px 33px 33px;
        -webkit-border-radius: 33px 33px 33px 33px;
        //border: 3px solid #ffffff;
        border: 2px solid #002EB8;
        background-color: #ffffff; //#a8a8a8;
        padding: 10px;
        margin-top: 0px;
        margin-left: 250px;
        margin-right: 250px;

        color: #002EB8;
        font-weight: bold;
        font-size: 20px;
    }
</style>

<div id="acpl-header">

    <h4 class="box">APPLICATION FOR AUDIO READING SERVICE RADIO</h4>

    <p>
        Allen County Public Library * Audio Reading Service
    </p>

    <p>
        7615 DiSalle Blvd * Fort Wayne IN 46825 * 260.421.1376
    </p>

    <p>
        audioreader@acpl.info
    </p>

</div>