
<div class="container">
    <div class="panel panel-success">
        <div class="panel-heading">Success!</div>
        <div class="panel-body">
            <!-- Individual application success message -->
            <p id="ind" class="boxes">
                Thank You! Your application has been processed. We will send 
                your radio out within two business days. If you have any questions 
                please call 260.421.1376 or email: AudioReadingService@acpl.info 
            </p>
            
            <!-- Organization application success message -->
            <p id="org" class="boxes">
                Thank you! Your application has been processed. Staff from the 
                Audio Reading Service will contact you within two business days 
                regarding your radios. If you have any questions please call 
                260.421.1376 or email: AudioReadingService@acpl.info
            </p>
        </div>
    </div>
</div>

<script>
    $(document).ready(function(){
       // hide all success messages initially
       $('.boxes').hide();
       
       var option = '';
       var url = window.location.href;
       
       option = url.match(/page=(.*)/)[1];
       showMessage(option);
       
       function showMessage(id){
           $('#' + id).show();
       }
       
    });
</script>