<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>


<div class="container">
    <div class="panel panel-success">
        <div class="panel-heading">Success!</div>
        <div class="panel-body">
            <p>Your application is now being processes by the Audio Reading Service</p>
            <p>Thank You!</p>
        </div>
    </div>
</div>

